# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java 8 Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B verify --file pom.xml

    - name: Generate Jacoco Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v1.0.0

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

    - name: Create pull request
      if: ${{ github.event_name == 'push' }}
      uses: peter-evans/create-pull-request@v3.4.1
      with:
        title: "Autogenerated Jacoco Coverage Badge"
        body: >
          Autogenerated Jacoco coverage badge, generated by
          the [jacoco-badge-generator](https://github.com/cicirello/jacoco-badge-generator)
          GitHub action.
        commit-message: "Autogenerated Jacoco Coverage Badge"
        branch: create-pull-request/badge
        delete-branch: true

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
        retention-days: 7
